### ISSUE TITLE
Show a list of student that have not been spoken to for a long time (possible replacing Timeline?)

### ISSUE THREAD

**Issue by avandam** [avandam/StudentProgress#6]
On the group page: add a possibility to shown students you have not spoken for a long time. Some things to consider:
- Disregard the progress with status like filled in evaluation
- It can be a list, or an icon in the student view.

**Comment by avandam-fontys** [comment]
As I personally do not use the timeline, consider replacing the timeline with the number of progresses and the date of the last progress or something like that

**Comment by avandam-fontys** [comment]
When the student status is available, also the students that are stopped / inactive should possibly not be shown

**Comment by avandam-fontys** [comment]
With the redesign of the group overview page, this issue is also implemented
